# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8396830a53ccc62a15d8dee6ea953e2ac540f52a08d06dcda0b38745fc50d67221fbf3ee5ce87a31a849af50e03f7ec40ee9cd43b007eea13048fd3ee629aade

test:
  secret_key_base: ad5add412e525ccd2b1af95825d0ab035f22106aa3a0b11a2ddc24811cc830cb18aabe9c5b1ed1d2d127dfb0079c40c7cae8a0b08028453ffd629f297264e4b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
